[package]
name = "muninn"
version = "0.2.4"
authors = ["Sarah Renkhoff <sarah.renkhoff@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 3

[dependencies]
plotters = "^0.2.14"
gdk-pixbuf = "0.8.0"
glib = "0.9.3"
gdk = "0.12.1"

[dependencies.gtk]
version = "0.8.1"
features = ["v3_22"]

[dependencies.gio]
version = ""
features = ["v2_44"]
