[package]
name = "muninn"
version = "0.1.0"
authors = ["Sarah Renkhoff <sarah.renkhoff@gmail.com>"]
edition = "2018"

[dependencies]
plotters = "^0.2.14"
gdk-pixbuf = "0.8.0"

[dependencies.gtk]
version = "0.8.1"
features = ["v3_24"]

[dependencies.gio]
version = ""
features = ["v2_44"]